/* wickra-strategy-ci C ABI — generated by cbindgen; do not edit by hand. */

#ifndef WICKRA_STRATEGY_CI_H
#define WICKRA_STRATEGY_CI_H

#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

// Opaque handle wrapping a [`Session`].
typedef struct WickraStrategyCi WickraStrategyCi;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Create a handle. Returns null only on allocation failure.
WickraStrategyCi *wickra_strategy_ci_new(void);

// Free a handle. Null-safe.
//
// # Safety
// `handle` must be a pointer returned by [`wickra_strategy_ci_new`] and not
// already freed, or null.
void wickra_strategy_ci_free(WickraStrategyCi *handle);

// Run a command envelope and write the response JSON into `out`.
//
// Returns the response length in bytes (excluding the NUL). If that length is
// `< cap`, the response plus a NUL terminator is written to `out`; otherwise
// `out` is left untouched and the caller should retry with a `len + 1` buffer
// (the response is deterministic, so the second call is the same length).
// Returns `-1` for a null handle or command, `-2` for a non-UTF-8 command, and
// `-3` if a panic was caught (which never happens in normal operation).
// Internal errors are returned as an `{"ok":false,"error":...}` response with a
// non-negative length, not as a negative code.
//
// # Safety
// `handle` must come from [`wickra_strategy_ci_new`]; `cmd` must be a valid
// NUL-terminated string; and `out` must point to at least `cap` writable bytes
// (or be null when `cap` is 0 for a length query).
int32_t wickra_strategy_ci_command(WickraStrategyCi *handle,
                                   const char *cmd,
                                   char *out,
                                   uintptr_t cap);

// The crate version as a static NUL-terminated string.
const char *wickra_strategy_ci_version(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* WICKRA_STRATEGY_CI_H */
